### ISSUE TITLE
Create an autodeploy of the FairOS docs

### ISSUE THREAD

**Issue by crtahlin** [fairDataSociety/fairOS-docs#2]
The docs should be generated from the repo and deployed to:
- docs.fairos.fairdatasociety.org (fully working when DNS are set, I guess)
- some redirect from current location?

**Comment by crtahlin** [comment]
@jmozah and @IgorShadurin Discuss also including the instructions on how to spin up the stack on a server (written down by @IgorShadurin as notes currently)

**Comment by IgorShadurin** [comment]
@crtahlin Seems like the domain docs.fairos.fairdatasociety.org not tied to our host
